<%@ Page Title="" Language="C#" MasterPageFile="~/LabFormat.Master" AutoEventWireup="true" CodeBehind="EditEquipment.aspx.cs" Inherits="Lab3.EditEmployee" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="body" runat="server">

  <h1>Equipment</h1>
    <asp:GridView ID="GrdEquip" 
        runat="server"
        AutoGenerateColumns="false" 
        AutoGenerateEditButton="true" 
        AutoGenerateDeleteButton="true"
         DataKeyNames="equipmentID"
         DataSourceID="DSEquip"        
         EmptyDataText="No Equipment Found">
        <Columns>
            <asp:BoundField DataField="EquipmentID" HeaderText="EquipmentID" Visible="false" />
            <asp:BoundField DataField="EquipmentType" HeaderText=" Equipment Type" />
        </Columns>
    </asp:GridView>
    <br />

    <asp:Label ID="AddEquipLbl" runat="server" Text="Add Equipment"></asp:Label>
    <asp:TextBox ID="AddEquipTxt" runat="server"></asp:TextBox>
    <asp:Button ID="Save" runat="server" Text="Add" OnClick="Save_Click" />
    <asp:Label ID="LblSaveStatus" runat="server" Text=""></asp:Label>

    
    
    <asp:SqlDataSource
            ID="DSEquip"
            runat="server"
            ConnectionString="<%$ConnectionStrings:Lab3%>"
            SelectCommand="Select * from Equipment" 
            UpdateCommand="UPDATE Equipment SET EquipmentType = @EquipmentType where EquipmentID = @EquipmentID" 
            DeleteCommand="DELETE Equipment where EquipmentID = @EquipmentID">        
     </asp:SqlDataSource>


</asp:Content>
