<%@ Page Title="" Language="C#" MasterPageFile="~/LabFormat.Master" AutoEventWireup="true" CodeBehind="EditEmployee.aspx.cs" Inherits="Lab3.WebForm1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="body" runat="server">
  <h1>Employee</h1>
    <asp:GridView ID="GrdEquip" 
        runat="server"
        AutoGenerateColumns="false" 
        AutoGenerateEditButton="true" 
        AutoGenerateDeleteButton="true"
         DataKeyNames="EmployeeID"
         DataSourceID="DSEquip"        
         EmptyDataText="No Employee Found">
        <Columns>
            <asp:BoundField DataField="EmployeeID" HeaderText="EmployeeID" Visible="false" />
            <asp:BoundField DataField="EmpFirstName" HeaderText=" Equipment First Name" />
            <asp:BoundField DataField="EmpLastName" HeaderText=" Equipment Last Name" />
        </Columns>
    </asp:GridView>
    <br />

    <asp:Label ID="AddEmployeeLbl" runat="server" Text="Add Employee:"></asp:Label>
    <br />
    <asp:Label ID="EmployeeFirstName" runat="server" Text="FirstName"></asp:Label>
    <asp:TextBox ID="AddEmployeeFirstTxt" runat="server"></asp:TextBox>
    <br />
    <asp:Label ID="EmployeeLastName" runat="server" Text="LastName"></asp:Label>
    <asp:TextBox ID="AddEmployeeLastTxt" runat="server"></asp:TextBox>
    <asp:Button ID="Save" runat="server" Text="Add" OnClick="Save_Click" />
    <asp:Label ID="LblSaveStatus" runat="server" Text=""></asp:Label>

    
    
    <asp:SqlDataSource
            ID="DSEquip"
            runat="server"
            ConnectionString="<%$ConnectionStrings:Lab3%>"
            SelectCommand="Select * from Employee" 
            UpdateCommand="UPDATE Employee SET EmpFirstName = @EmpFirstName , EmpLastName = @EmpLastName" 
            DeleteCommand="DELETE Employee where EmployeeID = @EmployeeID" >        
     </asp:SqlDataSource>


</asp:Content>
