<%@ Page Title="" Language="C#" MasterPageFile="~/LabFormat.Master" AutoEventWireup="true" CodeBehind="WarehouseAssign.aspx.cs" Inherits="Lab3.WarehouseAssign" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="body" runat="server">

    <asp:Label ID="LblCustomer" runat="server" Text="Customer: "></asp:Label>
    &nbsp;
    <asp:Label ID="LblCustomerSelected" runat="server" Text="" Font-Bold="true"></asp:Label>


    <asp:Table ID="table1" runat="server">

    </asp:Table>
    <br />
    <br />
    <asp:Table ID="gridtable" runat="server">
         <asp:TableRow>
            <asp:TableCell ColumnSpan="3">
                <asp:GridView ID="GridWarehouse"
                    runat="server"
                    DataSourceID="dtasrcWarehouse"
                    CausesValidation="false"
                    AutoGenerateColumns="false"
                    AutoGenerateEditButton="true"
                    AutoGenerateDeleteButton="true"                    
                    DataKeyNames="WarehouseID"
                    CellPadding="3">
                    

                    <Columns>
                        <asp:BoundField DataField="WarehouseID" Visible="false" />
                        <asp:BoundField DataField="Location"  HeaderText="Location" />  
                        <asp:BoundField DataField="Description"  HeaderText="Description" />
                        <asp:BoundField DataField="Date"  HeaderText="Date" />  
                        
                    </Columns>
                </asp:GridView>

            </asp:TableCell>
        </asp:TableRow>
         </asp:Table>
    <br />
    <br />
    <br />
    <asp:Table ID="table2" runat="server">
        <asp:TableRow>
             <asp:TableCell>
                <asp:Label ID="LblLocation" runat="server" Text="Location:"></asp:Label>
            </asp:TableCell>
            <asp:TableCell>
                <asp:TextBox ID="TxtLocation" runat="server" TextMode="MultiLine" Rows="5"></asp:TextBox>
            </asp:TableCell>
             <asp:TableCell>
                <asp:RequiredFieldValidator ID="RfvLocation"
                    runat="server"
                    ControlToValidate="TxtLocation"
                    Text="Field Cannot Be Blank"
                    ForeColor="Red"
                    ValidationGroup="CreateItem"></asp:RequiredFieldValidator>
            </asp:TableCell>
        </asp:TableRow>
        <asp:TableRow>
             <asp:TableCell>
                <asp:Label ID="LblDescription" runat="server" Text="Description:"></asp:Label>
            </asp:TableCell>
            <asp:TableCell>
                <asp:TextBox ID="TxtDescription" runat="server" TextMode="MultiLine" Rows="5"></asp:TextBox>
            </asp:TableCell>
             <asp:TableCell>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator2"
                    runat="server"
                    ControlToValidate="TxtDescription"
                    Text="Field Cannot Be Blank"
                    ForeColor="Red"
                    ValidationGroup="CreateItem"></asp:RequiredFieldValidator>
            </asp:TableCell>
        </asp:TableRow>
                <asp:TableRow>
            <asp:TableCell>
                <asp:Label ID="LblDate" runat="server" Text="Date:" />
            </asp:TableCell>
            <asp:TableCell>
                <asp:TextBox ID="TxtDate" TextMode="Date" runat="server"></asp:TextBox>
            </asp:TableCell>
            <asp:TableCell>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator4"
                    runat="server"
                    ControlToValidate="TxtDate"
                    Text="Field Cannot Be Blank"
                    ForeColor="Red"
                    ValidationGroup="CreateItem"></asp:RequiredFieldValidator>
            </asp:TableCell>
        </asp:TableRow>
        <asp:TableRow>
            <asp:TableCell>
                <asp:Button ID="Savebtn" runat="server" Text="Save to Database" OnClick="Savebtn_Click" ValidationGroup="CreateItem" />
            </asp:TableCell>
            <asp:TableCell>
                <asp:Label ID="LblStatus"
                    runat="server"
                    ForeColor="Green"></asp:Label>
            </asp:TableCell>
        </asp:TableRow>
       

   </asp:Table>

     <asp:SqlDataSource ID="dtasrcWarehouse"
        runat="server"
        ConnectionString="<%$ConnectionStrings:Lab3%>"
        SelectCommand="SELECT warehouseID, location, description, date from warehouse WHERE WAREHOUSE.CustomerID = @CustomerID"
        DeleteCommand="DELETE WAREHOUSE where WarehouseID = @WarehouseID"
        UpdateCommand="UPDATE WAREHOUSE SET Date = @Date, Location = @Location, Description = @Description WHERE WarehouseID = @WarehouseID">
        <SelectParameters>
            <asp:SessionParameter Name="CustomerID" SessionField="SelectedCustomerID" />
        </SelectParameters>
         
    </asp:SqlDataSource>
</asp:Content>
