<%@ Page Title="" Language="C#" MasterPageFile="~/LabFormat.Master" AutoEventWireup="true" CodeBehind="WarehouseAssign.aspx.cs" Inherits="Lab3.WarehouseAssign" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="body" runat="server">

    <asp:Label ID="LblCustomer" runat="server" Text="Customer: "></asp:Label>
    &nbsp;
    <asp:Label ID="LblCustomerSelected" runat="server" Text="" Font-Bold="true"></asp:Label>


    <div class="row justify-content-center">
        <h1 class="display-4">Assign to Warehouse</h1>
    </div>
    <br />
    <br />
    <div class="row justify-content-center">
    <asp:GridView ID="GridWarehouse"
        runat="server"
        DataSourceID="dtasrcWarehouse"
        CausesValidation="false"
        AutoGenerateColumns="false"
        AutoGenerateEditButton="true"
        AutoGenerateDeleteButton="true"
        DataKeyNames="WarehouseID"
        CellPadding="3">


        <Columns>
            <asp:BoundField DataField="WarehouseID" Visible="false" />
            <asp:BoundField DataField="Location" HeaderText="Location" />
            <asp:BoundField DataField="Description" HeaderText="Description" />
            <asp:BoundField DataField="Date" HeaderText="Date" />

        </Columns>
    </asp:GridView>
        </div>

    <br />
    <br />
    <br />

    <asp:Label ID="LblLocation" runat="server" Text="Location:"></asp:Label>

    <div class="form-group">
        <asp:DropDownList ID="DdlLocation" CssClass="form-control" runat="server">

            <asp:ListItem Selected="True">Select</asp:ListItem>
            <asp:ListItem>Gallery 3 Bays</asp:ListItem>
            <asp:ListItem>Warehouse R1</asp:ListItem>
            <asp:ListItem>Warehouse R2</asp:ListItem>
            <asp:ListItem>Warehouse R3</asp:ListItem>
            <asp:ListItem>Warehouse R4</asp:ListItem>
            <asp:ListItem>Warehouse R5</asp:ListItem>
            <asp:ListItem>Warehouse L1</asp:ListItem>
            <asp:ListItem>Warehouse L2</asp:ListItem>
            <asp:ListItem>Warehouse L3</asp:ListItem>
            <asp:ListItem>Warehouse L4</asp:ListItem>
            <asp:ListItem>Warehouse L5</asp:ListItem>
            <asp:ListItem>Trailer 1, Nose</asp:ListItem>
            <asp:ListItem>Trailer 1, Middle</asp:ListItem>
            <asp:ListItem>Trailer 1, Doors</asp:ListItem>
            <asp:ListItem>Trailer 2, Nose</asp:ListItem>
            <asp:ListItem>Trailer 2, Middle</asp:ListItem>
            <asp:ListItem>Trailer 2, Doors</asp:ListItem>
            <asp:ListItem>Trailer 3, Nose</asp:ListItem>
            <asp:ListItem>Trailer 3, Middle</asp:ListItem>
            <asp:ListItem>Trailer 3, Doors</asp:ListItem>
            <asp:ListItem>Trailer 4, Nose</asp:ListItem>
            <asp:ListItem>Trailer 4, Middle</asp:ListItem>
            <asp:ListItem>Trailer 4, Doors</asp:ListItem>
            <asp:ListItem>Trailer 5, Nose</asp:ListItem>
            <asp:ListItem>Trailer 5, Middle</asp:ListItem>
            <asp:ListItem>Trailer 5, Doors</asp:ListItem>
            <asp:ListItem>Trailer 6, Nose</asp:ListItem>
            <asp:ListItem>Trailer 6, Middle</asp:ListItem>
            <asp:ListItem>Trailer 6, Doors</asp:ListItem>
            <asp:ListItem>Trailer 7, Nose</asp:ListItem>
            <asp:ListItem>Trailer 7, Middle</asp:ListItem>
            <asp:ListItem>Trailer 7, Doors</asp:ListItem>
            <asp:ListItem>Trailer 8, Nose</asp:ListItem>
            <asp:ListItem>Trailer 8, Middle</asp:ListItem>
            <asp:ListItem>Trailer 8, Doors</asp:ListItem>
        </asp:DropDownList>
    </div>

    <asp:RequiredFieldValidator ID="RfvLocation"
        runat="server"
        ControlToValidate="DdlLocation"
        Text="Field Cannot Be Blank"
        ForeColor="Red"
        InitialValue="Select"
        ValidationGroup="CreateItem"></asp:RequiredFieldValidator>
    <div class="form-group">
        <label>Description</label>
        <asp:TextBox ID="TxtDescription" runat="server" Placeholder="Description" CssClass="form-control" TextMode="MultiLine" Rows="5"></asp:TextBox>
    </div>

    <asp:RequiredFieldValidator ID="RequiredFieldValidator2"
        runat="server"
        ControlToValidate="TxtDescription"
        Text="Field Cannot Be Blank"
        ForeColor="Red"
        ValidationGroup="CreateItem"></asp:RequiredFieldValidator>

    <div class="form-group">
        <label>Date</label>
        <asp:TextBox ID="TxtDate" TextMode="Date" CssClass="form-control" runat="server"></asp:TextBox>
    </div>
    <asp:RequiredFieldValidator ID="RequiredFieldValidator4"
        runat="server"
        ControlToValidate="TxtDate"
        Text="Field Cannot Be Blank"
        ForeColor="Red"
        ValidationGroup="CreateItem"></asp:RequiredFieldValidator>
    <div class="text-center">
    <asp:Button ID="Savebtn" runat="server" Text="Save to Database" class="btn btn-success" OnClick="Savebtn_Click" ValidationGroup="CreateItem" />
    <asp:Label ID="LblStatus"
        runat="server"
        ForeColor="Green"></asp:Label>
        </div>
    <asp:SqlDataSource ID="dtasrcWarehouse"
        runat="server"
        ConnectionString="<%$ConnectionStrings:Lab3%>"
        SelectCommand="SELECT warehouseID, location, description, date from warehouse WHERE WAREHOUSE.CustomerID = @CustomerID"
        DeleteCommand="DELETE WAREHOUSE where WarehouseID = @WarehouseID"
        UpdateCommand="UPDATE WAREHOUSE SET Date = @Date, Location = @Location, Description = @Description WHERE WarehouseID = @WarehouseID">
        <SelectParameters>
            <asp:SessionParameter Name="CustomerID" SessionField="SelectedCustomerID" />
        </SelectParameters>

    </asp:SqlDataSource>
</asp:Content>
